version: '3'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local

services:
  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USERNAME=miguel
      - MARIADB_PASSWORD=miguel
      - MARIADB_DATABASE=forecast
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M 
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup
    networks: 
      - default
  
  v1:
    build: /tmp/workflow/serviceV1/
    command: gunicorn v1:app -b :8080
    environment:
      - HOST=db
    ports:
      - 8001:8080
    links: 
      - db

  v2:
    build: /tmp/workflow/serviceV2/
    command: gunicorn v2:app -b :8080
    environment:
      - API_KEY="YOUR API KEY (AEMET)"
    ports:
      - 8002:8080